ClassCheck-Website-main/website/auth.py
import mysql.connector
from flask import Blueprint, request, redirect, url_for, render_template, jsonify, session, flash
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint('auth', __name__)

def get_db_connection():
    conn = mysql.connector.connect(
        host='localhost',  # MySQL sunucunuzun adresi
        user='root',  # MySQL kullanıcı adı
        password='',  # MySQL şifresi
        database='classcheck'  # Kullanmak istediğiniz veritabanı
    )
    return conn

@auth.route('/login', methods=['POST'])
def login():
    email = request.form['email']
    password = request.form['password']
    
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    
    # Öğretmen tablosundan kullanıcı kontrolü
    cursor.execute("SELECT * FROM teachers WHERE teacher_email=%s", (email,))
    teacher = cursor.fetchone()
    
    if teacher and check_password_hash(teacher['teacher_password'], password):
        session['teacher_id'] = teacher['teacher_id']
        return redirect(url_for('views.teacher_login'))
    
    # Yetkili kullanıcı kontrolü
    cursor.execute("SELECT * FROM authorized WHERE authorized_email=%s", (email,))
    authorized_user = cursor.fetchone()
    
    if authorized_user and authorized_user['authorized_password'] == password:
        session['authorized_id'] = authorized_user['authorized_id']
        return redirect(url_for('views.authorized_login'))
    
    # Kullanıcı bulunamazsa hata mesajı göster
    return render_template('login.html', invalid_login=True)

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        teacher_id = request.form['teacher_id']
        teacher_name = request.form['teacher_name']
        teacher_surname = request.form['teacher_surname']
        email = request.form['email']
        password = request.form['password']
        
        conn = get_db_connection()
        cursor = conn.cursor(dictionary=True)

        cursor.execute("SELECT * FROM teachers WHERE teacher_email=%s", (email,))
        existing_teacher = cursor.fetchone()
        
        if existing_teacher:
            flash('User already exists!', 'error')
            cursor.close()
            conn.close()
            return redirect(url_for('views.signup'))
        
        hashed_password = generate_password_hash(password, method='pbkdf2:sha256')
        cursor.execute("INSERT INTO teachers (teacher_id, teacher_name, teacher_surname, teacher_email, teacher_password) VALUES (%s, %s, %s, %s, %s)", 
                       (teacher_id, teacher_name, teacher_surname, email, hashed_password))
        conn.commit()
        cursor.close()
        conn.close()
        
        flash('User successfully registered!', 'success')
        return redirect(url_for('views.login'))
    
    return render_template('signup.html')

@auth.route('/add_teacher', methods=['POST'])
def add_teacher():
    try:
        teacher_id = request.form['teacher_id']
        teacher_name = request.form['teacher_name']
        teacher_surname = request.form['teacher_surname']
        email = request.form['email']
        password = request.form['password']

        # Boş alan kontrolü
        if not teacher_id or not teacher_name or not teacher_surname or not email or not password:
            return jsonify({'success': False, 'message': 'All fields are required!'})

        conn = get_db_connection()
        cursor = conn.cursor(dictionary=True)

        cursor.execute("SELECT * FROM teachers WHERE teacher_id=%s OR teacher_email=%s", (teacher_id, email))
        existing_teacher = cursor.fetchone()

        if existing_teacher:
            cursor.close()
            conn.close()
            return jsonify({'success': False, 'message': 'Teacher already exists!'})

        hashed_password = generate_password_hash(password, method='pbkdf2:sha256')
        cursor.execute("INSERT INTO teachers (teacher_id, teacher_name, teacher_surname, teacher_email, teacher_password) VALUES (%s, %s, %s, %s, %s)", 
                       (teacher_id, teacher_name, teacher_surname, email, hashed_password))
        conn.commit()
        cursor.close()
        conn.close()

        return jsonify({'success': True, 'message': 'Teacher successfully added!'})
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)})

@auth.route('/remove_teacher', methods=['POST'])
def remove_teacher():
    try:
        teacher_id = request.form['teacher_id']

        # Boş alan kontrolü
        if not teacher_id:
            return jsonify({'success': False, 'message': 'Teacher ID is required!'})

        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("DELETE FROM teachers WHERE teacher_id=%s", (teacher_id,))
        conn.commit()
        cursor.close()
        conn.close()

        return jsonify({'success': True, 'message': 'Teacher successfully removed!'})
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)})

@auth.route('/add_course', methods=['POST'])
def add_course():
    try:
        course_id = request.form['course_id']
        course_name = request.form['course_name']
        course_day = request.form['course_day']
        lesson_start_time = request.form['lesson_start_time']
        lesson_end_time = request.form['lesson_end_time']
        class_name = request.form['class_name']
        teacher_id = request.form['teacher_id']  # Yeni eklenen satır

        # Boş alan kontrolü
        if not course_id or not course_name or not course_day or not lesson_start_time or not lesson_end_time or not class_name or not teacher_id:
            return jsonify({'success': False, 'message': 'All fields are required!'})

        conn = get_db_connection()
        cursor = conn.cursor(dictionary=True)

        cursor.execute("SELECT * FROM courses WHERE course_id=%s", (course_id,))
        existing_course = cursor.fetchone()

        if existing_course:
            cursor.close()
            conn.close()
            return jsonify({'success': False, 'message': 'Course already exists!'})

        cursor.execute("INSERT INTO courses (course_id, course_name, course_day, attendance_start_time, attendance_end_time, class_name, teacher_id) VALUES (%s, %s, %s, %s, %s, %s, %s)", 
                       (course_id, course_name, course_day, lesson_start_time, lesson_end_time, class_name, teacher_id))  # Teacher ID eklendi
        conn.commit()
        cursor.close()
        conn.close()

        return jsonify({'success': True, 'message': 'Course successfully added!'})
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)})

@auth.route('/remove_course', methods=['POST'])
def remove_course():
    try:
        course_id = request.form['course_id']
        course_name = request.form['course_name']
        course_day = request.form['course_day']

        # Boş alan kontrolü
        if not course_id or not course_name or not course_day:
            return jsonify({'success': False, 'message': 'All fields are required!'})

        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("DELETE FROM courses WHERE course_id=%s AND course_name=%s AND course_day=%s", 
                       (course_id, course_name, course_day))
        conn.commit()
        cursor.close()
        conn.close()

        return jsonify({'success': True, 'message': 'Course successfully removed!'})
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)})

@auth.route('/add_student', methods=['POST'])
def add_student():
    try:
        student_id = request.form['student_id']
        student_name = request.form['student_name']
        student_surname = request.form['student_surname']

        # Boş alan kontrolü
        if not student_id or not student_name or not student_surname:
            return jsonify({'success': False, 'message': 'All fields are required!'})

        conn = get_db_connection()
        cursor = conn.cursor(dictionary=True)

        cursor.execute("SELECT * FROM students WHERE student_id=%s", (student_id,))
        existing_student = cursor.fetchone()

        if existing_student:
            cursor.close()
            conn.close()
            return jsonify({'success': False, 'message': 'Student already exists!'})

        cursor.execute("INSERT INTO students (student_id, student_name, student_surname) VALUES (%s, %s, %s)", 
                       (student_id, student_name, student_surname))
        conn.commit()
        cursor.close()
        conn.close()

        return jsonify({'success': True, 'message': 'Student successfully added!'})
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)})

@auth.route('/remove_student', methods=['POST'])
def remove_student():
    try:
        student_id = request.form['student_id']

        # Boş alan kontrolü
        if not student_id:
            return jsonify({'success': False, 'message': 'Student ID is required!'})

        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("DELETE FROM students WHERE student_id=%s", (student_id,))
        conn.commit()
        cursor.close()
        conn.close()

        return jsonify({'success': True, 'message': 'Student successfully removed!'})
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)})

@auth.route('/filter_students', methods=['POST'])
def filter_students():
    course_id = request.form.get('course_id')
    course_day = request.form.get('course_day')
    lesson_start_time = request.form.get('lesson_start_time')
    class_name = request.form.get('class_name')

    query = """
        SELECT s.student_id, s.student_name, s.student_surname, a.attendance_id
        FROM students s
        LEFT JOIN attendance a ON s.student_id = a.student_id
        LEFT JOIN courses c ON a.course_id = c.course_id

ClassCheck-Website-main/website/templates/add_course.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add/Remove Course</title>
    <link
      href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <style>
      .button-bg {
        background: #190087;
      }
      .button-bg:hover {
        background-color: #150073;
      }
      .button-active {
        background-color: #3e00b3;
      }
      .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgb(0, 0, 0);
        background-color: rgba(0, 0, 0, 0.4);
        padding-top: 60px;
      }
      .modal-content {
        background-color: #fefefe;
        margin: 5% auto;
        border: 1px solid #888;
        width: 30%;
        border-radius: 20px;
      }
      .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
        position: relative;
        top: -2px;
        right: 5px;
      }
      .close:hover,
      .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
      }
      .message-success {
        color: green;
        background-color: #d4edda;
        border-color: #c3e6cb;
        padding: 10px;
        border-radius: 5px;
      }
      .message-error {
        color: red;
        background-color: #ffcccc;
        border-color: #f5c6cb;
        padding: 10px;
        border-radius: 5px;
      }
      .password-container {
        position: relative;
      }
      .toggle-password {
        position: absolute;
        top: 50%;
        right: 10px;
        transform: translateY(-50%);
        cursor: pointer;
      }
    </style>
  </head>
  <body>
    <div class="flex flex-col justify-stretch h-full w-full my-6 md:mb-0 gap-6">
      <form
        id="add_course_form"
        action="{{ url_for('auth.add_course') }}"
        method="POST"
        class="mt-4"
      >
        <div id="userAlreadyExistError" class="error-message"></div>
        <label for="course_id" class="block mb-2">Course ID:</label>
        <input
          type="text"
          id="course_id"
          name="course_id"
          class="w-full p-2 border border-gray-300 rounded mb-2 input-field"
        />

        <label for="course_name" class="block mb-2">Course Name:</label>
        <input
          type="text"
          id="course_name"
          name="course_name"
          class="w-full p-2 border border-gray-300 rounded mb-4 input-field"
        />

        <label for="course_day" class="block mb-2">Course Day: </label>
        <input
          type="number"
          id="course_day"
          name="course_day"
          class="w-full p-2 border border-gray-300 rounded mb-4 input-field"
          placeholder="Please enter number between 1-7, (For example, 1 is Monday)"
        />
        
        <label for="teacher_id" class="block mb-2">Teacher ID:</label>
        <input
          type="text"
          id="teacher_id"
          name="teacher_id"
          class="w-full p-2 border border-gray-300 rounded mb-4 input-field"
        />
        
        <label for="lesson_start_time" class="block mb-2"
          >Lesson Start Time:</label
        >
        <input
          type="time"
          id="lesson_start_time"
          name="lesson_start_time"
          class="w-full p-2 border border-gray-300 rounded mb-4 input-field"
        />

        <label for="lesson_end_time" class="block mb-2">Lesson End Time:</label>
        <input
          type="time"
          id="lesson_end_time"
          name="lesson_end_time"
          class="w-full p-2 border border-gray-300 rounded mb-4 input-field"
        />

        <label for="class_name" class="block mb-2">Class Name:</label>
        <input
          type="text"
          id="class_name"
          name="class_name"
          class="w-full p-2 border border-gray-300 rounded mb-4 input-field"
        />

        <button
          id="add_course_button"
          class="button-bg text-white font-bold py-3 px-6 mt-4 rounded-lg"
        >
          Add Course
        </button>
      </form>

      <form
        id="remove_course_form"
        action="{{ url_for('auth.remove_course') }}"
        method="POST"
        class="mt-4"
      >
        <label for="course_id_remove" class="block mb-2">Course ID:</label>
        <input
          type="text"
          id="course_id_remove"
          name="course_id"
          class="w-full p-2 border border-gray-300 rounded mb-2 input-field"
        />

        <label for="course_name_remove" class="block mb-2">Course Name:</label>
        <input
          type="text"
          id="course_name_remove"
          name="course_name"
          class="w-full p-2 border border-gray-300 rounded mb-4 input-field"
        />

        <label for="course_day_remove" class="block mb-2">Course Day:</label>
        <input
          type="number"
          id="course_day_remove"
          name="course_day"
          class="w-full p-2 border border-gray-300 rounded mb-4 input-field"
        />

        <button
          id="remove_course_button"
          class="button-bg text-white font-bold py-3 px-6 mt-4 rounded-lg"
        >
          Remove Course
        </button>
      </form>

      <div id="myModal" class="modal">
        <div class="modal-content">
          <span class="close">&times;</span>
          <p id="modal-message"></p>
        </div>
      </div>
    </div>
    <script>
      function togglePassword() {
        var passwordField = document.getElementById("password");
        var passwordToggle = document.querySelector(".toggle-password");
        if (passwordField.type === "password") {
          passwordField.type = "text";
          passwordToggle.textContent = "👁️";
        } else {
          passwordField.type = "password";
          passwordToggle.textContent = "👁️";
        }
      }

      document
        .getElementById("add_course_form")
        .addEventListener("submit", function (event) {
          event.preventDefault(); // Sayfanın yeniden yüklenmesini engelle
          var form = event.target;
          var formData = new FormData(form);

          fetch(form.action, {
            method: "POST",
            body: formData,
          })
            .then((response) => response.json())
            .then((data) => {
              var modal = document.getElementById("myModal");
              var modalMessage = document.getElementById("modal-message");
              if (data.success) {
                modalMessage.textContent = data.message;
                modalMessage.className = "message-success";
              } else {
                modalMessage.textContent = data.message;
                modalMessage.className = "message-error";
              }
              modal.style.display = "block";
            })
            .catch((error) => {
              console.error("Error:", error);
              var modal = document.getElementById("myModal");
              var modalMessage = document.getElementById("modal-message");
              modalMessage.textContent = "An unexpected error occurred.";
              modal.style.display = "block";
            });
        });

      document
        .getElementById("remove_course_form")
        .addEventListener("submit", function (event) {
          event.preventDefault(); // Sayfanın yeniden yüklenmesini engelle
          var form = event.target;
          var formData = new FormData(form);

          fetch(form.action, {
            method: "POST",
            body: formData,
          })
            .then((response) => response.json())
            .then((data) => {
              var modal = document.getElementById("myModal");
              var modalMessage = document.getElementById("modal-message");
              if (data.success) {
                modalMessage.textContent = data.message;
                modalMessage.className = "message-success";
              } else {
                modalMessage.textContent = data.message;
                modalMessage.className = "message-error";
              }
              modal.style.display = "block";
            })
            .catch((error) => {
              console.error("Error:", error);
              var modal = document.getElementById("myModal");
              var modalMessage = document.getElementById("modal-message");
              modalMessage.textContent = "An unexpected error occurred.";
              modal.style.display = "block";
            });
        });

      document.getElementsByClassName("close")[0].onclick = function () {
        var modal = document.getElementById("myModal");
        modal.style.display = "none";
      };

      window.onclick = function (event) {
        var modal = document.getElementById("myModal");
        if (event.target == modal) {
          modal.style.display = "none";
        }
      };
    </script>
  </body>
</html>

ClassCheck-Website-main/website/templates/add_teacher.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add/Remove Teacher</title>
    <link
      href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <style>
      .button-bg {
        background: #190087;
      }
      .button-bg:hover {
        background-color: #150073;
      }
      .button-active {
        background-color: #3e00b3;
      }
      .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgb(0, 0, 0);
        background-color: rgba(0, 0, 0, 0.4);
        padding-top: 60px;
      }
      .modal-content {
        background-color: #fefefe;
        margin: 5% auto;
        border: 1px solid #888;
        width: 30%;
        border-radius: 20px;
      }
      .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
        position: relative;
        top: -2px;
        right: 5px;
      }
      .close:hover,
      .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
      }
      .message-success {
        color: green;
        background-color: #d4edda;
        border-color: #c3e6cb;
        padding: 10px;
        border-radius: 5px;
      }
      .message-error {
        color: red;
        background-color: #ffcccc;
        border-color: #f5c6cb;
        padding: 10px;
        border-radius: 5px;
      }
      .password-container {
        position: relative;
      }
      .toggle-password {
        position: absolute;
        top: 22px;
        right: 10px;
        transform: translateY(-50%);
        cursor: pointer;
        width: 24px;
        height: 24px;
      } 
    </style>
  </head>
  <body>
    <div class="flex flex-col h-full w-full my-6 md:mb-0 gap-6">
      <form
        id="add_teacher_form"
        action="{{ url_for('auth.add_teacher') }}"
        method="POST"
        class="mt-4"
      >
        <div id="userAlreadyExistError" class="error-message"></div>
        <label for="teacher_id" class="block mb-2">Teacher ID:</label>
        <input
          type="text"
          id="teacher_id"
          name="teacher_id"
          class="w-full p-2 border border-gray-300 rounded mb-2 input-field"
        />

        <label for="teacher_name" class="block mb-2">Name:</label>
        <input
          type="text"
          id="teacher_name"
          name="teacher_name"
          class="w-full p-2 border border-gray-300 rounded mb-4 input-field"
        />

        <label for="teacher_surname" class="block mb-2">Surname:</label>
        <input
          type="text"
          id="teacher_surname"
          name="teacher_surname"
          class="w-full p-2 border border-gray-300 rounded mb-4 input-field"
        />

        <label for="email" class="block mb-2">E-mail:</label>
        <input
          type="email"
          id="email"
          name="email"
          class="w-full p-2 border border-gray-300 rounded mb-4 input-field"
          placeholder="someone@example.com"
        />

        <label for="password" class="block mb-2">Password:</label>
        <div class="password-container">
          <input
            type="password"
            id="password"
            name="password"
            class="w-full p-2 border border-gray-300 rounded mb-4 input-field"
            placeholder="••••••••"
          />
          <span class="toggle-password" onclick="togglePassword()">
            <img
              src="{{ url_for('static', filename='images/hide_password.png') }}"
              alt="Show Password"
              id="toggle-password-icon"
            />
          </span>
        </div>

        <label for="confirm_password" class="block mb-2"
          >Confirm Password:</label
        >
        <div class="password-container relative">
          <input
            type="password"
            id="confirm_password"
            name="confirm_password"
            class="w-full p-2 border border-gray-300 rounded mb-4 input-field"
            placeholder="••••••••"
          />
          <span class="toggle-password" onclick="toggleConfirmPassword()" >
            <img
              src="{{ url_for('static', filename='images/hide_password.png') }}"
              alt="Show Password"
              id="toggle-confirm-password-icon"
              
            />
          </span>
        </div>

        <button
          id="add_teacher_button"
          class="button-bg text-white font-bold py-3 px-6 mt-4 rounded-lg"
        >
          Add Teacher
        </button>
      </form>

      <form
        id="remove_teacher_form"
        action="{{ url_for('auth.remove_teacher') }}"
        method="POST"
        class="mt-4"
      >
        <label for="teacher_id_remove" class="block mb-2">Teacher ID:</label>
        <input
          type="text"
          id="teacher_id_remove"
          name="teacher_id"
          class="w-full p-2 border border-gray-300 rounded mb-2 input-field"
        />

        <button
          id="remove_teacher_button"
          class="button-bg text-white font-bold py-3 px-6 mt-4 rounded-lg"
        >
          Remove Teacher
        </button>
      </form>

      <div id="myModal" class="modal">
        <div class="modal-content">
          <span class="close">&times;</span>
          <p id="modal-message"></p>
        </div>
      </div>
    </div>
    <script>
      function togglePassword() {
        var passwordField = document.getElementById("password");
        var passwordToggle = document.getElementById("toggle-password-icon");
        if (passwordField.type === "password") {
          passwordField.type = "text";
          passwordToggle.src =
            "{{ url_for('static', filename='images/show_password.png') }}";
        } else {
          passwordField.type = "password";
          passwordToggle.src =
            "{{ url_for('static', filename='images/hide_password.png') }}";
        }
      }

      function toggleConfirmPassword() {
        var confirmPasswordField = document.getElementById("confirm_password");
        var confirmPasswordToggle = document.getElementById(
          "toggle-confirm-password-icon"
        );
        if (confirmPasswordField.type === "password") {
          confirmPasswordField.type = "text";
          confirmPasswordToggle.src =
            "{{ url_for('static', filename='images/show_password.png') }}";
        } else {
          confirmPasswordField.type = "password";
          confirmPasswordToggle.src =
            "{{ url_for('static', filename='images/hide_password.png') }}";
        }
      }

      document
        .getElementById("add_teacher_form")
        .addEventListener("submit", function (event) {
          event.preventDefault(); // Prevent page reload
          var form = event.target;
          var formData = new FormData(form);

          // Define modal elements
          var modal = document.getElementById("myModal");
          var modalMessage = document.getElementById("modal-message");

          // Check for empty fields
          var teacher_id = document.getElementById("teacher_id").value;
          var teacher_name = document.getElementById("teacher_name").value;
          var teacher_surname =
            document.getElementById("teacher_surname").value;
          var email = document.getElementById("email").value;
          var password = document.getElementById("password").value;
          var confirmPassword =
            document.getElementById("confirm_password").value;

          if (
            !teacher_id ||
            !teacher_name ||
            !teacher_surname ||
            !email ||
            !password ||
            !confirmPassword
          ) {
            modalMessage.textContent = "All fields are required!";
            modalMessage.className = "message-error";
            modal.style.display = "block";
            return;
          }

          // Password validation
          if (password !== confirmPassword) {
            modalMessage.textContent = "Passwords do not match!";
            modalMessage.className = "message-error";
            modal.style.display = "block";
            return;
          }

          // Password complexity check
          if (!isPasswordValid(password)) {
            modalMessage.textContent =
              "Your password must be 8-16 characters, include at least one lowercase letter, one uppercase letter, one number, and one special character.";
            modalMessage.className = "message-error";
            modal.style.display = "block";
            return;
          }

          function isPasswordValid(password) {
            var passwordRegex =
              /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&()_+}{":;'?/>,.])[0-9a-zA-Z!@#$%^&()_+}{":;'?/>,.]{8,16}$/;
            return passwordRegex.test(password);
          }

          fetch(form.action, {
            method: "POST",
            body: formData,
          })
            .then((response) => response.json())
            .then((data) => {
              if (data.success) {
                modalMessage.textContent = data.message;
                modalMessage.className = "message-success";
              } else {
                modalMessage.textContent = data.message;
                modalMessage.className = "message-error";
              }
              modal.style.display = "block";
            })
            .catch((error) => {
              console.error("Error:", error);
              modalMessage.textContent = "An unexpected error occurred.";
              modalMessage.className = "message-error";
              modal.style.display = "block";
            });
        });

      document
        .getElementById("remove_teacher_form")
        .addEventListener("submit", function (event) {
          event.preventDefault(); // Prevent page reload
          var form = event.target;
          var formData = new FormData(form);

          var modal = document.getElementById("myModal");
          var modalMessage = document.getElementById("modal-message");

          fetch(form.action, {
            method: "POST",
            body: formData,
          })
            .then((response) => response.json())
            .then((data) => {
              if (data.success) {
                modalMessage.textContent = data.message;
                modalMessage.className = "message-success";
              } else {
                modalMessage.textContent = data.message;
                modalMessage.className = "message-error";
              }
              modal.style.display = "block";
            })
            .catch((error) => {
              console.error("Error:", error);
              modalMessage.textContent = "An unexpected error occurred.";
              modalMessage.className = "message-error";
              modal.style.display = "block";
            });
        });

      document.getElementsByClassName("close")[0].onclick = function () {
        var modal = document.getElementById("myModal");
        modal.style.display = "none";
      };

      window.onclick = function (event) {
        var modal = document.getElementById("myModal");
        if (event.target == modal) {
          modal.style.display = "none";
        }
      };
    </script>
  </body>
</html>